### ISSUE TITLE
Coder-Server can't connect because of this Error

### ISSUE THREAD

**Issue by fdervisi** [coder/deploy-code-server#77]
Hi,

Unfortunately the Code Server always crash, to fix it I need to restart the service. Can somebody please help??

```
     Memory: 781.5M
     CGroup: /system.slice/system-code\x2dserver.slice/code-server@coder.service
             ├─21912 /usr/lib/code-server/lib/node /usr/lib/code-server
             ├─21931 /usr/lib/code-server/lib/node /usr/lib/code-server
             ├─21943 /usr/lib/code-server/lib/coder-cloud-agent bind --code-server-addr=127.0.0.1:34247
             ├─21959 /usr/lib/code-server/lib/node /usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap-fork --type=ptyHost
             ├─22198 /usr/lib/code-server/lib/node /usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap-fork --type=watcherServiceParcel
             ├─22212 /usr/lib/code-server/lib/node /usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap-fork --type=extensionHost --uriTransformerPath=>
             ├─22247 /home/coder/mcdonalds_poc/cdk_patch_manager_asg_windows_2019/.venv/bin/python /home/coder/.local/share/code-server/extensions/ms-python.pyth>
             ├─22263 /usr/lib/code-server/lib/node /usr/lib/code-server/vendor/modules/code-oss-dev/extensions/json-language-features/server/dist/node/jsonServer>
             ├─22276 /usr/lib/code-server/lib/node /home/coder/.local/share/code-server/extensions/amazonwebservices.aws-toolkit-vscode-1.35.0/dist/src/ssmDocume>
             ├─22338 /usr/bin/bash
             ├─22429 /usr/lib/code-server/lib/node /home/coder/.local/share/code-server/extensions/amazonwebservices.aws-toolkit-vscode-1.35.0/dist/src/stepFunct>
             └─23050 /home/coder/mcdonalds_poc/cdk_patch_manager_asg_windows_2019/.venv/bin/python /home/coder/.local/share/code-server/extensions/ms-python.pyth>

Jan 24 13:15:58 cdk-coder-1 code-server[21912]: [13:15:58] [127.0.0.1][2bbd0ffa][ExtensionHostConnection] <22000> Extension Host Process exited with code: 0, sig>
Jan 24 13:16:09 cdk-coder-1 code-server[21912]: [13:16:09] [127.0.0.1][699f94d1][ManagementConnection] New connection established.
Jan 24 13:16:11 cdk-coder-1 code-server[21912]: [13:16:11] [127.0.0.1][8b43cf37][ExtensionHostConnection] New connection established.
Jan 24 13:16:11 cdk-coder-1 code-server[21912]: [13:16:11] [127.0.0.1][8b43cf37][ExtensionHostConnection] <22212> Launched Extension Host Process.
Jan 24 14:14:02 cdk-coder-1 code-server[21912]: [2022-01-24T14:14:02.897Z] info  2022/01/24 14:14:02 [ERR] yamux: Failed to read header: failed to get reader: fa>
Jan 24 14:14:02 cdk-coder-1 code-server[21912]: [2022-01-24T14:14:02.898Z] info  2022-01-24 14:14:02.896 [WARN]        <proxy.go:48>        code-server proxy exi>
Jan 24 14:14:09 cdk-coder-1 code-server[21912]: [14:14:09] [127.0.0.1][699f94d1][ManagementConnection] The client has disconnected, will wait for reconnection 3h>
Jan 24 14:14:09 cdk-coder-1 code-server[21912]: Error: Unexpected SIGPIPE
Jan 24 14:14:09 cdk-coder-1 code-server[21912]:     at process.<anonymous> (/usr/lib/code-server/vendor/modules/code-oss-dev/out/bootstrap.js:1:370)
Jan 24 14:14:09 cdk-coder-1 code-server[21912]:     at process.emit (events.js:400:28)
```

**Comment by bpmct** [comment]
this is fixed in the latest version
